version: 2
updates:
  - package-ecosystem: npm
    directory: /clickup-task-workspace
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /json-text-normalizer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development